Backend: Vitis
ClockPeriod: 5
ClockUncertainty: 27%
HLSConfig:
  LayerName:
    dense:
      Precision:
        bias: auto
        result: auto
        weight: auto
      Trace: false
    dense_1:
      Precision:
        bias: auto
        result: auto
        weight: auto
      Trace: false
    dense_1_softmax:
      Precision:
        result: auto
      Trace: false
    dense_relu:
      Precision:
        result: auto
      Trace: false
    input_layer:
      Precision:
        result: auto
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision:
      default: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'my_hls_prj/keras_model.keras'
OutputDir: my_hls_prj
OutputPredictions: null
Part: xcvu13p-flga2577-2-e
ProjectName: myproject
Stamp: eac1f19a
Version: 1.0.0
WriterConfig:
  Namespace: null
  WriteTar: false
  WriteWeightsTxt: true
